[package]
name = "info-app"
version = "0.1.0"
edition = "2021"


[dependencies]
wmi = "0.9"
serde = "1.0.136"
rui = "0.1.5"
tokio = { version = "1.17.0", features = ["sync", "rt", "macros", "rt-multi-thread"] }
futures = "0.3.21"